### ISSUE TITLE
base.decode(...).buffer returns 1 byte too long buffer.

### ISSUE THREAD

**Issue by algiuxass** [qntm/base32768#11]
Title says it all:
base.decode(...).buffer returns 1 byte too long buffer.

Example:
```
base.decode("h").buffer.length == 1
base.decode("hi").buffer.length == 3
base.decode("hii").buffer.length == 3
base.decode("hiii").buffer.length == 5
base.decode("hiiii").buffer.length == 5
```

**Comment by algiuxass** [comment]
Hmm, I didn't notice that there wasn't any documentation about `.buffer` so I guess no one is using it.

**Comment by qntm** [comment]
You're correct, `base32768` operates on `Uint8Array`s, not `ArrayBuffer`s. A `Uint8Array` is a view of part, not necessarily all, of an underlying `ArrayBuffer`. Internally, `base32768` allocates an `ArrayBuffer` which is in some cases is [one byte longer than eventually necessary](https://github.com/qntm/base32768/blob/main/src/index.js#L96-L98), and then returns a `Uint8Array` which views all but the final, unnecessary byte. This is simpler from a programming perspective and it also saves memory. (I think.)

However!

Although this is all technically defensible, these ergonomics may be surprising and produce unexpected results. This could be characterised as a design flaw.

I will leave `base32768` as it is for now. But if it turns out that more people than just you are running into this point of confusion, it might be worth altering the code to make the `Uint8Array` view the *whole* of its underlying `ArrayBuffer` in every case. We'll see.
