### ISSUE TITLE
If this supports UTF16, then why cant I use Uint16array?

### ISSUE THREAD

**Issue by CodeStarrk** [qntm/base32768#18]
I'm not sure I understand, but I can only use Uint8array, not Uint16array?

**Comment by qntm** [comment]
Base32768 is an encoding for converting an input, arbitrary binary data, to an output, Unicode text. `base32768` is a JavaScript implementation of this encoding. For the purposes of this implementation, it made sense to choose one data type to use for the binary data and one data type to use for the Unicode text. I chose `Uint8Array` for the binary data, and `String` for the Unicode text. Let me explain my choices.

By binary data, what I mean is a finite sequence of 0 or more *bytes* or *octets* - 8-bit numbers. Originally I used [`Buffer`s](https://nodejs.org/api/buffer.html), because I was working in Node.js and the `Buffer` class is specifically intended for this purpose. However, `Buffer`s only exist in Node.js. They were added because at the time JavaScript in general did not have any kind of specific tools for handling binary data at all. This meant that `base32768` was of no use in, say, a web browser. Later on, JavaScript added the various [`TypedArray`s](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray), including [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array). Then, Node.js made it so that `Buffer` was a subclass `Uint8Array` - anywhere a `Uint8Array` was used, a `Buffer` could be used. Because `Uint8Array` was part of the JavaScript specification and available universally, this became the more logical choice, and I updated `base32768` to use `Uint8Array`s.

There are various other `TypedArray` types, like `Uint16Array`. If you genuinely are starting with a `Uint16Array`, converting it to a `Uint8Array` for consumption by `base32768` is very straightforward:

```js
const uint8Array = new Uint8Array(uint16Array.buffer, uint16Array.byteOffset, uint16Array.byteLength)
```

However, I think it's relatively unlikely that you would be starting with your binary data in a `Uint16Array`. That could imply that your input data was UTF-16-encoded Unicode text, which in turn could imply some kind of mistake. The Base32768 encoding is for sending *arbitrary* binary data through a Unicode text-based system. If your data isn't arbitrary, it's just Unicode text, then... you don't need Base32768. Just send the Unicode text directly. It'll be fine.

As for the output... JavaScript's data type for Unicode text is the `String`. There are some minor quirks associated with `String`, but it didn't make sense to use anything else. Again, if you genuinely do want to go on and encode that `String` using UTF-16 and make a `Uint16Array` yourself, this is quite straightforward:

```js
const uint16Array = Uint16Array.from(string, c => c.charCodeAt(0))
```

However, again, I think it's relatively unlikely that this is what you want. The Base32768 encoding is optimised so that if this `String` is then encoded using UTF-16, the encoded binary data would take up a minimal number of bytes. However, Base32768 does not perform this encoding to UTF-16 itself. The assumption is that you are interacting with a Unicode text-based system, like a text-based API, or maybe just copying and pasting the text into an input field in a web browser... and the UTF-16 encoding is something which happens internally. Again, if the system accepts binary data, just send the unmodified binary data directly. It'll be fine.

Thank you for a good question.
