### ISSUE TITLE
Consideration when string will be stored in text files

### ISSUE THREAD

**Issue by ZYinMD** [qntm/base32768#26]
First of all, thanks a lot for creating `base32768`.

I'm experimenting with converting binary data into text, then store as text files in the filesystem. 

<details>
  <summary>The reason why I do it may not be your interest, so I fold it.</summary>

> I need to ship an offline .html to my users, who can simply double click to open it, and it'll be a fancy SPA that runs on `file:///`. It can't read anything from the file system, except css js and images via src="" tags. So, I use `const database = "a_long_long_string"` inside a .js file to provide data to the app. 

</details>

Since text files are UTF-8, this package seems to lose the edge. (As far as my tests, when my instruction is "hey I have this big string, please write it to file", both browser and nodejs will write UTF-8, so I guess it's not up to me to change)

So I tested different ways to convert binary data to string, for instance, base32768, base64, and TextDecoder.

Base32768 works as intended, of course.

Base64 seems to do really well, it's faster than base32768 and produces smaller text files. I guess it's because each base64 char is 1 byte in UTF8, correct? Your README says it's 75% efficient while base32768 is 63%, which is consistent with my output file size.

`TextDecoder` is 20x more performant than the 2 above, but the conversion can't be reversed if the input Uint8Array contains bytes from 128-255 and I don't understand why:

<details>
  <summary>TextDecoder test code:</summary>

```js
function convertToStringThenBack(input: Uint8Array) {
  const string = new TextDecoder().decode(input.buffer);
  const back = new TextEncoder().encode(string);
  const isEqual =
    back.length === input.length &&
    back.every((value, index) => value === input[index]);
  if (isEqual) console.log("good");
  else console.log("bad");
}

convertToStringThenBack(new Uint8Array([1, 10, 100, 127])); // good
convertToStringThenBack(new Uint8Array([1, 10, 100, 128])); // bad


```

</details>

Performance is a big deal because my data is very large, even if it means I'll have to add an extra step after `TextDecoder` to sanitize the string, however I simply don't know how to make it work.

Regardless, do you have any comments to whatever I wrote above? Thanks very much!

**Comment by qntm** [comment]
If you're trying to write your binary out to disk in the form of a UTF-8 text string then you're correct that Base32768 is not the right choice.

`TextEncoder` is also not the right choice because, as you have discovered, it isn't designed to encode arbitrary binary data *as* text, it's intended to encode arbitrary *text* as UTF-8 binary data. Likewise `TextDecoder` is intended to decode UTF-8 binary data back to text. If the binary data isn't valid UTF-8, then you'll get replacement characters �. In your example, `new Uint8Array([1, 10, 100, 128])` is not valid UTF-8.

Base64 does support arbitrary binary data and will give you about 75% efficiency. 3 bytes of data will be encoded as 4 characters of Unicode text, which will encode as 4 bytes on disk as UTF-8. So 1MB of data will take up about 1.33MB on disk, which is pretty good. In terms of performance I would have expected that `btoa` would be pretty fast at converting binary to Base64 and `atob` would be pretty fast at converting Base64 back to the binary.
